title: about machines, consoles & numbers
description: writings, thoughts & cool stuff i care about
baseurl: ""        
url: "https://LAK3SHORE.github.io"
theme: null        
markdown: kramdown
permalink: /:categories/:title/
timezone: Etc/UTC

# Navigation (edit labels/links as you like)
nav:
  - { label: "home",     url: "/" }
  - { label: "about",    url: "/about/" }
  - { label: "projects", url: "/projects/" }
  - { label: "reading list",  url: "/reading/" }

# Socials (optional)
social:
  github:  LAK3SHORE
  twitter: _csalinas_
  email: essal.cristobal@gmail.com
